### ISSUE TITLE
Not found: main file "dist/index.js" in package

### ISSUE THREAD

**Issue by gluons** [earthchie/JQL.js#2]
เรียกใช้ `require('jqljs')` ไม่ได้ครับ เนื่องจากใน [`package.json` ใส่ `main` เป็น `dist/index.js`](https://github.com/earthchie/JQL.js/blob/00ab8352a14f3955c4067730d30aae0cd379063d/package.json#L4) แต่ใน [`./dist` เป็นไฟล์ `jql.min.js`](https://github.com/earthchie/JQL.js/blob/00ab8352a14f3955c4067730d30aae0cd379063d/dist/jql.min.js)

สามารถดูบน [unpkg](https://unpkg.com/jqljs@0.3.1)

**Comment by zapkub** [comment]
just update ! sorry #3 will fix this issues!
